// GitHub API連携 - Jules用Issue自動作成
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_OWNER = process.env.GITHUB_OWNER || "morodas-ai";
const GITHUB_REPO = process.env.GITHUB_REPO || "morodas-os";

interface CreateIssueParams {
    title: string;
    body: string;
    labels?: string[];
}

interface GitHubIssue {
    number: number;
    html_url: string;
    state: string;
}

/**
 * GitHub Issueを作成してJulesに渡す
 */
export async function createGitHubIssue(params: CreateIssueParams): Promise<GitHubIssue | null> {
    if (!GITHUB_TOKEN) {
        console.warn("[GitHub] GITHUB_TOKEN not set. Skipping issue creation.");
        return null;
    }

    const url = `https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/issues`;

    const response = await fetch(url, {
        method: "POST",
        headers: {
            Authorization: `Bearer ${GITHUB_TOKEN}`,
            Accept: "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "Content-Type": "application/json",
        },
        body: JSON.stringify({
            title: params.title,
            body: params.body,
            labels: ["jules", ...(params.labels || [])],
        }),
    });

    if (!response.ok) {
        const error = await response.text();
        console.error(`[GitHub] Failed to create issue: ${response.status} ${error}`);
        throw new Error(`GitHub Issue作成失敗: ${response.status}`);
    }

    const issue = await response.json();
    console.log(`[GitHub] Issue #${issue.number} created: ${issue.html_url}`);
    return {
        number: issue.number,
        html_url: issue.html_url,
        state: issue.state,
    };
}

/**
 * GitHub Issueのステータスを取得
 */
export async function getGitHubIssue(issueNumber: number): Promise<GitHubIssue | null> {
    if (!GITHUB_TOKEN) return null;

    const url = `https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/issues/${issueNumber}`;

    const response = await fetch(url, {
        headers: {
            Authorization: `Bearer ${GITHUB_TOKEN}`,
            Accept: "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    });

    if (!response.ok) return null;

    const issue = await response.json();
    return {
        number: issue.number,
        html_url: issue.html_url,
        state: issue.state,
    };
}

/**
 * JulesタスクのIssue本文を生成
 */
export function buildJulesIssueBody(task: {
    title: string;
    description?: string | null;
    priority?: string;
}): string {
    return `## 🏗️ Jules Task Assignment

**Priority:** ${task.priority || "medium"}

### Description
${task.description || "No description provided."}

### Instructions for Jules
- This task was automatically created from MORODAS OS Task Manager.
- Please create a Pull Request when the implementation is complete.
- Add the label \`jules-complete\` when done.

---
*Auto-generated by MORODAS OS × Antigravity*`;
}

/**
 * GitHub Tokenが設定されているか確認
 */
export function isGitHubConfigured(): boolean {
    return !!GITHUB_TOKEN;
}
